const sc = document.getElementById('stars-container');
if (sc) for (let i = 0; i < 80; i++) { const s = document.createElement('div'); s.className = 'star'; s.style.cssText = `left:${Math.random()*100}%;top:${Math.random()*100}%;--d:${1.5+Math.random()*3}s;--o:${0.3+Math.random()*0.7};width:${1+Math.random()*3}px;height:${1+Math.random()*3}px;animation-delay:${Math.random()*3}s`; sc.appendChild(s); }
const bgMusic = document.getElementById('background-music'); bgMusic.volume = 0.3; function playMusic() { bgMusic.play().catch(() => {}); } document.addEventListener('click', playMusic, { once: true }); document.addEventListener('scroll', playMusic, { once: true });
const isFirstVisit = !localStorage.getItem('visited');
if (isFirstVisit) { localStorage.setItem('visited', 'true'); setTimeout(() => { const intro = document.getElementById('intro-overlay'); intro.classList.add('fade-out'); setTimeout(() => { intro.style.display = 'none'; const videoOverlay = document.getElementById('intro-video-overlay'); videoOverlay.style.display = 'flex'; const video = document.getElementById('intro-video'); video.onended = () => { videoOverlay.style.display = 'none'; showWebsite(); }; }, 950); }, 5000); } else { document.getElementById('intro-overlay').style.display = 'none'; showWebsite(); }
function showWebsite() { const websiteContainer = document.getElementById('website-container'); websiteContainer.style.display = 'block'; document.body.style.overflow = 'auto'; setupScrollReveal(); setupOutroTrigger(); }
function setupScrollReveal() { const observer = new IntersectionObserver((entries) => { entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); observer.unobserve(e.target); } }); }, { threshold: 0.1 }); document.querySelectorAll('.reveal').forEach(el => observer.observe(el)); }
let outroShown = false; function setupOutroTrigger() { window.addEventListener('scroll', () => { if (outroShown) return; const scrollBottom = window.scrollY + window.innerHeight; const docHeight = document.documentElement.scrollHeight; if (scrollBottom >= docHeight - 100) { outroShown = true; showOutro(); } }); }
function showOutro() { const website = document.getElementById('website-container'); const outro = document.getElementById('outro-overlay'); website.style.display = 'none'; document.body.style.overflow = 'hidden'; outro.style.display = 'flex'; const video = document.getElementById('outro-video'); video.onended = () => { setTimeout(() => { outro.style.opacity = '0'; outro.style.transition = 'opacity 0.8s ease'; setTimeout(() => { outro.style.display = 'none'; showReplayButton(); }, 800); }, 1000); }; }
function showReplayButton() { const btn = document.createElement('button'); btn.innerHTML = '🔄 شاهد الموقع مرة أخرى'; btn.className = 'replay-btn'; btn.onclick = replayWebsite; document.body.appendChild(btn); }
function replayWebsite() { const website = document.getElementById('website-container'); const outro = document.getElementById('outro-overlay'); const btn = document.querySelector('.replay-btn'); if (btn) btn.remove(); outro.style.display = 'none'; outro.style.opacity = '1'; outro.style.transition = ''; website.style.display = 'block'; document.body.style.overflow = 'auto'; window.scrollTo(0, 0); document.querySelectorAll('.reveal.visible').forEach(el => { el.classList.remove('visible'); }); setupScrollReveal(); }